version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env      # now points at Supabase
    depends_on:
      - redis
    ports:
      - '5000:5000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./frontend/.env     
    depends_on:
      - backend
    ports:
      - '5173:80'
