export { default as About } from './About'
export { default as Lyrics } from './Lyrics'
export { default as Playing } from './Playing'
export { default as Playlists } from './Playlists'
export { default as Profile } from './Profile'
export { default as Rooms } from './Rooms'